import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Autogenerated sidebar from docs folder structure
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
